package.json, pnpm-lock.yaml, src/components/Timetable.tsx, src/hooks/useGetGeneralRequired.ts, src/hooks/useGetMajorRequired.ts, src/hooks/useGetMajotElective.ts, src/hooks/useGetTimetable.ts, src/hooks/usePostTimetable.ts, src/index.css, src/pages/DesiredCreditActivity.tsx, src/pages/OnboardingActivity.tsx, src/pages/TimetableSelectionActivity.tsx, src/schemas/courseSchema.ts, src/schemas/timetableSchema.ts, src/stackflow.ts
- resolve #8 
- 시간표 선택 페이지를 구현했습니다.
https://github.com/user-attachments/assets/c7c9adaa-2d0e-45b6-9b1a-aa0ddbc8864d
- 지금 시간표 생성 API에 문제가 있는 것 같아 API는 문제 해결 되는 대로 연결할 예정입니다.
- 시간표 스크롤을 위해 [embla-carousel](https://www.embla-carousel.com/) 의존성을 추가하였습니다.
- 시간표 공유 페이지에서도 사용할 예정
=> feat: 시간표 선택 페이지 구현

package.json, pnpm-lock.yaml, src/App.tsx, src/components/Hint.tsx, src/components/Timetable.tsx, src/index.css, src/machines/studentMachine.ts, src/pages/OnboardingActivity.tsx, src/pages/TimetableSelectionActivity.tsx, src/pages/TimetableSharingActivity.tsx, src/schemas/timetableSchema.ts, src/stackflow.ts
- resolve #16 
- [embla-carousel](https://www.embla-carousel.com/)로 시간표 템플릿 스크롤을 구현했습니다.
- `html2canvas`로 사진 저장 기능을 구현했습니다.
- Web Share API로 링크 공유 기능을 구현했습니다.
https://github.com/user-attachments/assets/92bbe198-29a8-40c3-9ab6-451bad25b1cf
=> feat: 시간표 공유 페이지 구현

src/components/Timetable.tsx, src/components/TimetableSkeleton.tsx, src/pages/DesiredCreditActivity.tsx, src/pages/TimetableSelectionActivity.tsx, src/pages/TimetableSharingActivity.tsx, src/schemas/courseSchema.ts, src/schemas/timetableSchema.ts
- resolve #20 
- 시간표 선택 페이지의 API를 연결했습니다.
- 희망 학점 선택 페이지에서 사용자가 제출 버튼을 누르면 mutation 발생시키기
- 시간표 선택 페이지에서는 `useMutationState()` 훅으로 희망 학점 선택 페이지에서 발생시킨 mutation의 상태 가져오기 
- mutation의 상태가 "pending"일 때 보여줄 Skeleton UI를 구현했습니다.
https://github.com/user-attachments/assets/b58c7d4c-e293-4f41-9d0a-60d596352bb8
- zod 스키마로 응답을 검증할 때 `timestamp` 필드에서 에러가 발생해 `timestamp`의 타입을 `z.string().datetime()`이 아닌 `z.string()`으로 바꿨습니다.
=> feat: 시간표 선택 페이지 API 연결

src/pages/CourseSelectionActivity.tsx
- 희망 학점 액티비티의 Params 타입 변경으로 인한 빌드 에러가 나서 과목 선택 페이지에서 희망 학점 선택 페이지로 적절한 데이터를 보내도록 수정했습니다.
=> fix: 과목 선택 페이지에서 희망 학점 선택 페이지로 적절한 데이터를 보내도록 수정

src/components/AdmissionYearInput.tsx, src/components/GradeInput.tsx, src/machines/studentMachine.ts, src/schemas/studentSchema.ts
- [cc48c70](https://github.com/yourssu/soongpt-web/pull/19/commits/cc48c70b3d4d6e119982d509e362043310477700)에서 상태 머신을 React Context로 관리하면서 학년 입력, 입학년도 입력 필드의 초기값이 잘못 설정되는 이슈가 있어 해결하였습니다.
=> fix: 입학년도 및 학년 입력 필드의 초기값을 0으로 설정

src/components/Timetable.tsx, src/components/TimetableSharingTemplate.tsx, src/components/TimetableSkeleton.tsx, src/hooks/useGetTimetable.ts, src/pages/CourseSelectionActivity.tsx, src/pages/DesiredCreditActivity.tsx, src/pages/OnboardingActivity.tsx, src/pages/TimetableSelectionActivity.tsx, src/pages/TimetableSharingActivity.tsx, src/schemas/courseSchema.ts, src/schemas/timetableSchema.ts
- resolved #24 
- 시간표 공유 페이지 API를 연결하였습니다.
- 모바일 브라우저에서 주소 창과 하단 컨트롤 영역 때문에 화면이 잘리는 이슈가 있어 `vh` 단위를 `dvh` 단위로 수정하였습니다.
- `Suspense` 컴포넌트를 활용하기 위해 `useGetTimetable()` 훅을 Suspense Query로 변경하였습니다.
https://github.com/user-attachments/assets/775daafa-eae0-4b3e-892e-dbc1feeed2e1
=> feat: 시간표 공유 페이지 API 연결

src/components/SelectedCoursesBottomSheet.tsx, src/index.css, src/pages/CourseSelectionActivity.tsx
- #27 
- 모바일에서 bottomSheet를 드래그 했을 때 새로고침이 되지 않습니다.
=> fix: 모바일 기기 pull-to-refresh 해결

src/components/Timetable.tsx, src/hooks/usePostTimetable.ts, src/pages/OnboardingActivity.tsx, src/pages/TimetableSelectionActivity.tsx, src/schemas/errorSchema.ts, src/utils/error.ts
- #29 
- 다양한 error를 transform하는 transformError 함수를 작성하였습니다. (shout out to @EATSTEAK)
- 시간표 생성 실패 시 에러 텍스트를 출력합니다.
- status에 따른 렌더링을 미리 정의해놓고 썼는데 어떠신지요
=> fix: 시간표 생성 실패 시 예외 처리

src/components/TimetableSharingTemplate.tsx, src/pages/TimetableSelectionActivity.tsx, src/pages/TimetableSharingActivity.tsx, src/utils/error.ts
- resolve #30 
-  시간표 공유 버튼 클릭 시 링크가 아닌 사진이 공유되도록 수정하였습니다.
-  시간표 선택 페이지에서 muation이 없을 경우 자연스럽게 온보딩 페이지로 이동하도록 `replace()` 메서드에 animate: false 옵션을 주었습니다.
```ts
useEffect(() => {
if (!latestMutation) replace('OnboardingActivity', {}, { animate: false });
}, [latestMutation, replace]);
```
https://github.com/user-attachments/assets/2c6c7e26-9bd3-4598-ae95-a215dd9cd09b
=> fix: 시간표 공유 버튼 클릭 시 사진이 공유되도록 수정

src/hooks/usePostTimetable.ts
- #56 
- 시간표 생성 요청 시 timeout을 제거했습니다.
=> fix: 시간표 요청 시 timeout 제거

src/components/TimetableSharingTemplate.tsx
- resolve #54
- 시간표 템플릿 배경 및 헤더 색상을 수정했습니다.
=> fix: 시간표 템플릿 배경 및 헤더 색상 수정

package.json, pnpm-lock.yaml, src/pages/TimetableSharingActivity.tsx
- resolve #62 
- 공유하기에서 에러가 발생하면 현재 URL을 복사 후 토스트를 띄워줍니다.
https://github.com/user-attachments/assets/3dba2491-6e7f-4710-a12f-cafab98227f7
=> feat: 공유하기에서 에러가 발생하면 URL 복사 후 토스트 띄워주기

src/pages/TimetableSharingActivity.tsx
- resolve #62 
- URL 복사 실패 시 사용자 피드백을 위한 토스트 메시지를 띄워줍니다.
=> fix: URL 복사 실패 시 사용자 피드백을 위한 토스트 메시지 추가

.github/workflows/deploy.yml, package.json, pnpm-lock.yaml, src/App.tsx, src/pages/OnboardingActivity.tsx, src/utils/mixpanel.ts
- resolve #67 
- Mixpanel을 연결하여 사용자 이벤트를 추적합니다. (지금은 페이지 뷰만 추적될듯)
=> feat: Mixpanel 연결

src/components/Timetable.tsx, src/components/TimetableSharingTemplate.tsx
- resolve #69 
- `background-color`가 아닌 `background` 속성으로 배경 색상을 지정하도록 수정하였습니다.
- 디자인에 맞게 템플릿의 학생 정보 텍스트 색상을 수정하였습니다.
=> fix: 템플릿 배경 색상 적용 안되는 문제 수정

index.html
=> feat: 채널톡 코드 추가

src/App.tsx, src/components/CourseSelection/CourseSelection.tsx, src/components/TimetableSharingTemplate.tsx, src/pages/DesiredCreditActivity.tsx, src/pages/OnboardingActivity.tsx, src/pages/TimetableSelectionActivity.tsx, src/pages/TimetableSharingActivity.tsx, src/schemas/studentSchema.ts, src/utils/mixpanel.ts
- resolved #67 
- 숭피티 이벤트 텍소노미에 정의된 이벤트를 Mixpanel로 추적할 수 있도록 하였습니다.
=> feat: Mixpanel 이벤트 추적 추가

.github/workflows/deploy.yml, package.json, pnpm-lock.yaml, src/main.tsx, src/utils/sentry.ts
- resolve #75 
- 에러 추적을 위한 Sentry를 연결했습니다.
- Sentry DNS 환경 변수 추가
=> feat: 에러 추적을 위한 Sentry 연결

.gitignore, package.json, pnpm-lock.yaml, src/main.tsx, src/utils/sentry.ts, vite.config.ts
- resolve #75 
- 에러 추적을 위한 Sentry를 연결했습니다.
- Sentry 무료 플랜 계정 제한이 최대 1개라 yourssu-web 구글 계정을 만들었습니다.
=> feat: 에러 추적을 위한 Sentry 연동

src/components/RollingNumber.tsx, src/pages/DesiredCreditActivity.tsx
- resolve #83 
- 희망 학점 선택 페이지에서 채플 학점(0.5)이 반영되도록 수정했습니다.
https://github.com/user-attachments/assets/e3b6e6c2-28b5-440d-a381-7edbcf9081dd
=> fix: 희망 학점 선택 페이지에서 채플 학점이 반영 안되는 문제 수정

package.json, pnpm-lock.yaml, tailwind.config.js
- tailwind 관련 의존성 버전을 최신으로 업데이트 했어요.
- tailwind v4 에서 사용하지 않는 `tailwind.config.js` 파일을 제거했어요.
>
=> refactor: tailwind 버전업 및 tailwind.config.js 제거

tsconfig.app.json
- useDefineForClassFields 제거 (플젝 내 클래스 사용 안함)
- erasableSyntaxOnly: enum 제약 추가
>
=> chore: tsconfig 옵션 개선

eslint.config.js, package.json
- #89 
위 PR이 머지된 상황에서 리뷰를 받아 이를 반영하는 커밋이에요.
- jsx parser optons가 이미 플러그인에 존재함 : [코멘트](https://github.com/yourssu/soongpt-web/pull/89#discussion_r2213786298)
- 불필요한 mts 확장자 인식 : [코멘트](https://github.com/yourssu/soongpt-web/pull/89#discussion_r2213763282)
>
=> chore: #89(chore: 프로젝트 eslint, prettier 개선) 리뷰 반영

src/App.tsx
기존에 화면 최대 너비로 되어있던 콘텐츠 너비가 
모바일 퍼스트로서 최대 고정 너비를 가질 수 있도록 개선했어요.
큰 체인징이라 생각되어서 팀원분들의 리뷰가 필요해요. 일단 draft PR로 올려두겠습니다.
Stackflow의 컨테이너 포지셔닝이 
```css
position: absolute;
width: 100%;
height: 100%;
```
로 되어 있기 때문에, 가까운 엘리먼트에 `relative` 를 선언해주고 거기에 `max-width` 를 넣어주는 방식으로 해결했어요.
<br />
=> feat: 앱 화면에 최대 너비 추가

.github/workflows/deploy-alpha.pr.yml
알파에는 올려야되는데, 작업중이라 PR은 열어둬야하는 경우를 대비해서 
PR에 `alpha` 라벨을 붙여 알파 배포 타게팅을 수행할 수 있도록 하는 액션 스크립트를 작성했어요.
=> chore: PR 열어둔채로 알파에 배포하는 액션 작성

src/pages/CourseSelectionActivity/components/CourseSelectionSteps/MajorElectiveSelectionStep.tsx
- [전선 선택 > 최초 학년 변경시 발생하는 플리커링 해결](https://www.notion.so/yourssu/23f6915d6978806cabf2e4367f0c75ed?source=copy_link)
- 특정 학년의 전공선택 과목을 불러오는 로직을 Suspense 바운더리로 격리시켜 과목 선택 Suspense를 트리거하지 않도록 수정했어요.
https://github.com/user-attachments/assets/25c67dbd-55f2-490c-9ac1-dfb829daf91f
>
=> fix: 전공선택 스텝에 학년을 변경할 때 과목 선택 Suspense를 트리거 하지 않도록 수정

src/bootstrap/mixpanel.ts, src/hooks/useFilterCoursesByCategory.ts, src/pages/CourseSelectionActivity/components/CourseSelectionList.tsx, src/pages/CourseSelectionActivity/components/CourseSelectionSteps/MajorElectiveSelectionStep.tsx, src/pages/CourseSelectionActivity/index.tsx, src/pages/CourseSelectionActivity/type.ts, src/pages/DesiredCreditActivity/index.tsx, src/pages/TimetableSelectionActivity/index.tsx, src/schemas/studentSchema.ts
- 장바구니, 최대학점 다이얼로그 클릭시 이벤트 연동
- 시간표 선택 에러 이벤트를 error 객체 대신 필드 분리
- 선호 학점 이벤트 파라미터를 관련 학점 값으로 변경
- 전선 과목 다른 학년거 선택하면 로깅하게 구현
=> feat: 이벤트 로깅 미구현들 구현

src/pages/CourseSelectionActivity/index.tsx, src/pages/DesiredCreditActivity/index.tsx, src/pages/OnboardingActivity/index.tsx, src/pages/TimetableSelectionActivity/index.tsx, src/pages/WaitlistActivity/index.tsx, src/stackflow.ts
=> feat: 액티비티 코드 스플리팅 적용
